In [4]:
from numpy import array
A = array([[1,2,3], [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
from numpy import array
A = array([
    [1,2,3],
    [4,5,6]
])
print(A)
B = array([
    [1,2,3],
    [4,5,6]
])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [8]:
from numpy import array
A = array([
    [1,2,3],
    [4,5,6]
])
print(A)
B = array([
    [0.5,0.5,0.5],
    [0.5,0.5,0.5]
])
print(B)
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [10]:
from numpy import array
A = array([
    [1,2,3],
    [4,5,6]
])
print(A)
B = array([
    [1,2,3],
    [4,5,6]
])
print(B)
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [12]:
from numpy import array
A = array([
    [1,2,3],
    [4,5,6]
])
print(A)
B = array([
    [1,2,3],
    [4,5,6]
])
print(B)
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
from numpy import array
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
B = array([
    [1,2],
    [3,4]
])
print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


In [16]:
from numpy import array
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
B = array([0.5,0.5])
print(B)
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


In [18]:
from numpy import array
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
b = 0.5
print(b)
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
