In [1]:
from numpy import array
from numpy import tril
from numpy import triu
M = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])
print(M)
lower = tril(M)
print(lower)
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [3]:
from numpy import array
from numpy import diag
M = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])
print(M)
d = diag(M)
print(d)
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [5]:
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from numpy import array
from numpy.linalg import inv
Q = array([
    [1,0],
    [0,-1]
])
print(Q)
V = inv(Q)
print(V)
print(Q.T)
I = Q.dot(Q.T)