In [1]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


In [3]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [5]:
from numpy import array
from numpy.linalg import norm
from numpy import inf
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0
