In [1]:
from numpy import array
data = [11, 22, 33, 44, 55]
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [3]:
from numpy import array
data = [[11, 22],
        [33, 44],
        [55, 66]]
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [5]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0])
print(data[4])

11
55


In [7]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [11]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[-1])
print(data[-5])

55
11


In [13]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data[0,0])

11


In [15]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data[0,])

[11 22]


In [17]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [19]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [21]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


In [23]:
from numpy import array
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [25]:
from numpy import array
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])
split = 2
train, test = data[:split, :], data[split:, :]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [27]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [29]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data.shape)

(3, 2)


In [31]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [37]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data.shape)
data = data.reshape((data.shape[0]), 1)
print(data.shape)
print(data)

(5,)
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


In [39]:
from numpy import array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data.shape)
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
