In [2]:
from numpy import array
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [4]:
from numpy import array
from numpy.linalg import inv
A = array([
    [1.0,2.0],
    [3.0,4.0]
])
print(A)
B = inv(A)
print(B)
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [6]:
from numpy import array
from numpy import trace
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
b = trace(A)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [8]:
from numpy import array
from numpy.linalg import det
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
b = det(A)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [10]:
from numpy import array
from numpy.linalg import matrix_rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [12]:
from numpy import array
from numpy.linalg import matrix_rank
M0 = array([
    [0,0],
    [0,0]
])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
M1 = array([
    [1,2],
    [1,2]
])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
M2 = array([
    [1,2],
    [3,4]
])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2
