In [1]:
from numpy import array
l = [1.0, 2.0, 3.0]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [3]:
from numpy import empty
a = empty([3,3])
print(a)

[[4.67296746e-307 1.69121096e-306 9.34604358e-307]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]


In [15]:
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [23]:
from numpy import array
from numpy import vstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = vstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
from numpy import array
from numpy import hstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
