In [1]:
from numpy import array
from numpy import mean
v = array([1,2,3,4,5,6])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [3]:
from numpy import array
from numpy import mean
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)
col_mean = mean(M, axis=0)
print(col_mean)
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


In [5]:
from numpy import array
from numpy import var
v = array([1,2,3,4,5,6])
print(v)
result = var(v, ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


In [7]:
from numpy import array
from numpy import var
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)
col_var = var(M, ddof=1, axis=0)
print(col_var)
row_var = var(M, ddof=1, axis=1)
print(row_var)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


In [9]:
from numpy import array
from numpy import std
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)
col_std = std(M, ddof=1, axis=0)
print(col_std)
row_std = std(M, ddof=1, axis=1)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


In [15]:
from numpy import array
from numpy import cov
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma = cov(x,y)[0,1]
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


In [19]:
from numpy import array
from numpy import corrcoef
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
corr = corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


In [21]:
from numpy import array
from numpy import cov
X = array([
    [1,5,8],
    [3,5,11],
    [2,4,9],
    [3,6,10],
    [1,5,10]
])
print(X)
Sigma = cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]
