In [1]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [3]:
from numpy import array
A = array([
    [1, 2, 3],
    [1, 2, 3]
])
print(A)
b = 2
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [5]:
from numpy import array
A = array([
    [1, 2, 3],
    [1, 2, 3]
])
print(A)
b = array([1, 2, 3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [7]:
from numpy import array
A = array([
    [1, 2, 3],
    [1, 2, 3]
])
print(A.shape)
b = array([1, 2])
print(b.shape)
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 