In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
M = mean(A.T, axis=1)
print(M)
C = A - M
print(C)
V = cov(C.T)
print(V)
values, vectors = eig(V)
print(values)
print(vectors)
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[[4. 4.]
 [4. 4.]]
[8. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [3]:
from numpy import array
from sklearn.decomposition import PCA
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
pca = PCA(2)
pca.fit(A)
print(pca.components_)
print(pca.explained_variance_)
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8.00000000e+00 2.25080839e-33]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  4.44089210e-16]]
