In [1]:
from numpy import array
from scipy.linalg import svd
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [3]:
from numpy import array
from scipy.linalg import svd
from numpy import zeros
from numpy import diag
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)
Sigma = zeros((A.shape[0], A.shape[1]))
print(Sigma)
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(Sigma)
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [5]:
from numpy import array
from scipy.linalg import svd
from numpy import diag
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)
Sigma = diag(s)
print(Sigma)
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
from numpy import array
from numpy.linalg import pinv
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]
])
print(A)
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [9]:
from numpy import array
from scipy.linalg import svd
from numpy import zeros
from numpy import diag
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]
])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)
d = 1.0 / s
print(d)
D = zeros(A.shape)
print(D)
D[:A.shape[1], :A.shape[1]] = diag(d)
print(D)
B = VT.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-0.15248323 -0.82264747 -0.39450102 -0.37995913]
 [-0.34991837 -0.42137529  0.24279655  0.80065588]
 [-0.54735351 -0.0201031   0.69790998 -0.46143436]
 [-0.74478865  0.38116908 -0.5462055   0.04073761]]
[1.42690955 0.06268282]
[[-0.64142303 -0.7671874 ]
 [ 0.7671874  -0.64142303]]
[ 0.70081527 15.95333376]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0.70081527  0.        ]
 [ 0.         15.95333376]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [11]:
from numpy import array
from scipy.linalg import svd
from numpy import zeros
from numpy import diag
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)
Sigma = zeros((A.shape[0], A.shape[1]))
print(Sigma)
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
print(Sigma)
n_elements = 2
Sigma = Sigma[:, :n_elements]
print(Sigma)
VT = VT[:n_elements, :]
print(VT)
B = U.dot(Sigma.dot(VT))
print(B)
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[-0.19101157 -0.89266338  0.40824829]
 [-0.51371859 -0.26348917 -0.81649658]
 [-0.8364256   0.36568503  0.40824829]]
[9.69657342e+01 7.25578339e+00 1.48879510e-15]
[[-0.24139304 -0.25728686 -0.27318068 -0.2890745  -0.30496832 -0.32086214
  -0.33675595 -0.35264977 -0.36854359 -0.38443741]
 [ 0.53589546  0.42695236  0.31800926  0.20906617  0.10012307 -0.00882003
  -0.11776313 -0.22670623 -0.33564933 -0.44459242]
 [ 0.09975293 -0.01037753  0.23987452  0.05273845  0.0996209  -0.46517509
  -0.52300449 -0.23591804  0.593137    0.14935136]
 [-0.259848   -0.19489762 -0.10988774  0.9273013  -0.07153728 -0.05251768
  -0.04829915 -0.05415057 -0.07582496 -0.0603383 ]
 [-0.26312174 -0.0585767  -0.12150761 -0.05740164  0.9302533  -0.0441965
  -0.05005435 -0.07728074 -0.13808364 -0.12003039]
 [-0.34412869 -0.09157816  0.43274424 -0.05958094 -0.05492318  0.70339002
  -0.33412339 -0.23272698  0.08693936

In [13]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])
print(A)
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747 -6.47697214]
 [49.81310011 -1.91182038]
 [81.10462276  2.65333138]]
